# Generated by Django 5.2 on 2025-04-24 09:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_reason', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='Learner',
            new_name='learner',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='final_deadline',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='mid_deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Skill',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='Skill',
        ),
        migrations.AddField(
            model_name='unit',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 4, 24, 9, 52, 41, 460303, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='SkillReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.reason')),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.skill')),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='skill_reason_pair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='api.skillreason'),
            preserve_default=False,
        ),
    ]
